name: Compile LaTeX on push

# on:
#   push:
#     paths:
#       - '**.tex'

jobs:
  build_latex:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2

    - name: Install LaTeX
      run: |
        sudo apt update -y
        sudo apt-get install texlive-xetex -y
        sudo apt install texlive-fonts-extra -y
        
    - name: Compile LaTeX file
      run: |
        (cd industry && xelatex resume.tex)
        (cd academic && xelatex CirrculumVitae.tex)
      
